package android.zero.studio.widget.editor.symbolinput

fun buildFallbackSymbolGroups(): MutableList<SymbolGroup> {
    return mutableListOf(
        SymbolGroup("commonlyUsed", mutableListOf(
            SymbolItem(18, "←", null, 16, null),
            SymbolItem(20, "↑", null, 23, null),
            SymbolItem(19, "→", null, 17, null),
            SymbolItem(0, "\"", "\""),
            SymbolItem(0, "'", "'"),
            SymbolItem(0, ".", "."),
            SymbolItem(0, ",", ","),
            SymbolItem(0, "/", "/"),
            SymbolItem(0, "//", "//"),
            SymbolItem(21, "↓", null, 24, null),
            SymbolItem(0, ":", ":"),
            SymbolItem(0, ";", ";"),
            SymbolItem(0, "#", "#"),
            SymbolItem(0, "+", "+"),
            SymbolItem(0, "-", "-"),
            SymbolItem(0, "*", "*"),
            SymbolItem(0, "=", "="),
            SymbolItem(0, "|", "|"),
            SymbolItem(0, "~", "~"),
            SymbolItem(0, "(", "("),
            SymbolItem(0, ")", ")"),
            SymbolItem(0, "(\"", "(\""),
            SymbolItem(0, "\")", "\")"),
            SymbolItem(0, "{", "{"),
            SymbolItem(0, "}", "}"),
            SymbolItem(0, "()", "()", 0, "(\$T)"),
            SymbolItem(0, "[]", "[]", 0, "[\$T]"),
            SymbolItem(0, "{}", "{\$S\$T\$E}", 0, "{\$T}"),
            SymbolItem(0, "<", "<"),
            SymbolItem(0, ">", ">"),
            SymbolItem(0, "\\", "\\"),
            SymbolItem(0, "$", "$"),
            SymbolItem(0, "&", "&"),
            SymbolItem(0, "/*", "/**"),
            SymbolItem(0, "*/", "*/"),
            SymbolItem(22, "settings")
        )),
        SymbolGroup("Kotlin", mutableListOf(
            SymbolItem(9, "↹"),
            SymbolItem(18, "←"),
            SymbolItem(20, "↑"),
            SymbolItem(21, "↓"),
            SymbolItem(19, "→"),
            SymbolItem(0, "//", "//"),
            SymbolItem(0, "/*", "/*", 0, "*/"),
            SymbolItem(0, "\"", "\"\""),
            SymbolItem(0, "|", "|"),
            SymbolItem(0, "$", "$"),
            SymbolItem(0, "@", "@"),
            SymbolItem(0, "#", "#"),
            SymbolItem(0, "&", "&"),
            SymbolItem(0, "&&", "&&"),
            SymbolItem(0, "`", "`"),
            SymbolItem(0, "in", "in "),
            SymbolItem(0, "as", "as "),
            SymbolItem(0, "->", "->"),
            SymbolItem(0, "!", "!"),
            SymbolItem(0, "!!", "!!"),
            SymbolItem(0, "?.", "?."),
            SymbolItem(0, "?:", "?:"),
            SymbolItem(0, "[", "[]", 0, "["),
            SymbolItem(0, "]", "]"),
            SymbolItem(0, "{", "{}", 0, "{"),
            SymbolItem(0, "}", "}"),
            SymbolItem(0, "(", "()", 0, "("),
            SymbolItem(0, ")", ")"),
            SymbolItem(0, "<", "<>", 0, "<"),
            SymbolItem(0, ">", ">"),
            SymbolItem(0, "..<", "..<"),
            SymbolItem(0, "::", "::"),
            SymbolItem(0, "+", "+"),
            SymbolItem(0, "++", "++"),
            SymbolItem(0, "--", "--"),
            SymbolItem(0, "/", "/"),
            SymbolItem(0, "*", "*"),
            SymbolItem(0, "?", "?"),
            SymbolItem(0, ":", ":"),
            SymbolItem(0, ";", ";"),
            SymbolItem(0, "_", "_")
        )),
        SymbolGroup("Java", mutableListOf(
            SymbolItem(9, "↹"),
            SymbolItem(18, "←"),
            SymbolItem(20, "↑"),
            SymbolItem(21, "↓"),
            SymbolItem(19, "→"),
            SymbolItem(0, "//", "//"),
            SymbolItem(0, "/*", "/*", 0, "*/"),
            SymbolItem(0, "*/", "*/"),
            SymbolItem(0, ",", ","),
            SymbolItem(0, "{", "{}", 0, "{"),
            SymbolItem(0, "}", "}"),
            SymbolItem(0, "(", "()", 0, "("),
            SymbolItem(0, ")", ")"),
            SymbolItem(0, ";", ";"),
            SymbolItem(0, "=", "="),
            SymbolItem(0, "==", "=="),
            SymbolItem(0, "!=", "!="),
            SymbolItem(0, "<=", "<="),
            SymbolItem(0, ">=", ">="),
            SymbolItem(0, "+=", "+="),
            SymbolItem(0, "-=", "-="),
            SymbolItem(0, "*=", "*="),
            SymbolItem(0, "/=", "/="),
            SymbolItem(0, "\"", "\"\""),
            SymbolItem(0, "<", "<>", 0, "<"),
            SymbolItem(0, ">", ">"),
            SymbolItem(0, "+", "+"),
            SymbolItem(0, "-", "-"),
            SymbolItem(0, "*", "*"),
            SymbolItem(0, "/", "/"),
            SymbolItem(0, "?", "?"),
            SymbolItem(0, ":", ":"),
            SymbolItem(0, "_", "_"),
            SymbolItem(0, "new", "new "),
            SymbolItem(0, "null", "null"),
            SymbolItem(22, "settings")
        )),
        SymbolGroup("XML", mutableListOf(
            SymbolItem(9, "↹"),
            SymbolItem(18, "←"),
            SymbolItem(20, "↑"),
            SymbolItem(21, "↓"),
            SymbolItem(19, "→"),
            SymbolItem(0, "<", "<>", 0, "<"),
            SymbolItem(0, ">", ">"),
            SymbolItem(0, "<!--", "<!-- -->", 0, "<!--"),
            SymbolItem(0, "-->", "-->"),
            SymbolItem(0, "/", "/"),
            SymbolItem(0, "=", "="),
            SymbolItem(0, "\"", "\"\""),
            SymbolItem(0, ":", ":"),
            SymbolItem(0, "@", "@"),
            SymbolItem(0, "+", "+"),
            SymbolItem(0, "(", "()", 0, "("),
            SymbolItem(0, ")", ")"),
            SymbolItem(0, ";", ";"),
            SymbolItem(0, ",", ","),
            SymbolItem(0, ".", "."),
            SymbolItem(0, "?", "?"),
            SymbolItem(0, "|", "|"),
            SymbolItem(0, "\\", "\\"),
            SymbolItem(0, "&", "&"),
            SymbolItem(0, "[", "[]", 0, "["),
            SymbolItem(0, "]", "]"),
            SymbolItem(0, "{", "{}", 0, "{"),
            SymbolItem(0, "}", "}"),
            SymbolItem(0, "_", "_"),
            SymbolItem(0, "-", "-")
        ))
    )
}
